### ISSUE TITLE
小程序端

### ISSUE THREAD

**Issue by WangRongsheng** [Wang-Fulin-SDUWH/Autism#1]
请问，如何进行正确的小程序端部署呢？
希望能帮助我解决问题，我的邮箱：603329354@qq.com 或者微信 `wxMoonquakes`

**Comment by Wang-Fulin-SDUWH** [comment]
抱歉，因为个人使用的邮箱有多个，一直没有看到您的消息。小程序端部署，并不需要把Python代码转写成js，只需要通过Pycharm新建Flask项目，把原有的算法部署到本地服务器，通过小程序给服务器发送一些指令让服务器上的代码运行就可以啦！服务器的详细使用如果您需要的Demo话，可以再联系我，我最近有另外一个开源的GitHub扫描全能王项目，在本地服务器上用opencv实现了许多图像处理算法，并传递到小程序上，也可以给您分享。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wang-Fulin-SDUWH/FacialExpressionRecognition-With-AutismKids"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月26日(星期六) 下午5:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Wang-Fulin-SDUWH/FacialExpressionRecognition-With-AutismKids] 小程序端 (#1)





 
请问，如何进行正确的小程序端部署呢？
 ***@***.*** 或者微信 wxMoonquakes
